### ISSUE TITLE
.NET 5 BlazorServer app: 'WheelZoomJsFunctions' was undefined 

### ISSUE THREAD

**Issue by ferminv** [iso8859/BlazorWheelZoom#4]
Hello guys, im getting this error:
Error: Microsoft.JSInterop.JSException: Could not find 'WheelZoomJsFunctions.boundingRect' ('WheelZoomJsFunctions' was undefined).

I have everything defined as the readme.md file says. 

This is my _Host.cshtml: 

<!DOCTYPE html>
<html lang="es-ar">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ComitPresupuestosWeb</title>
    <base href="~/" />
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
    <link href="_content/MudBlazor/MudBlazor.min.css" rel="stylesheet" />
    <link href="css/site.css" rel="stylesheet" />
    <link href="ComitPresupuestosWeb.styles.css" rel="stylesheet" />
</head>
<body>
    <component type="typeof(App)" render-mode="Server" />

    <div id="blazor-error-ui">
        <environment include="Staging,Production">
            An error has occurred. This application may no longer respond until reloaded.
        </environment>
        <environment include="Development">
            An unhandled exception has occurred. See browser dev tools for details.
        </environment>
        <a href="" class="reload">Reload</a>
        <a class="dismiss">🗙</a>
    </div>

    <script src="_framework/blazor.server.js"></script>
    <script src="_content/MudBlazor/MudBlazor.min.js"></script>
    <script src="_content/wheel-zoom-blazor/wheelzoomblazor.js"></script>
    <script src="js/customFunctions.js"></script>

</body>
</html>

I have installed the library through Nuget Package Manager.

Thanks in advance..

**Comment by iso8859** [comment]
Hi,

There was an error in readme.md
I should have put 
```
<script src="_content/iso8859.blazor.wheel-zoom/wheelzoomblazor.js"></script>
```

Fixed now.

Remi

**Comment by ferminv** [comment]
It works like a charm now! You are the man Remi. Cheers

Fermin
